// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: kinnekode/restaurant/file/v1/file_service.proto

package v1

import (
	protobuf "github.com/kinneko-de/api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Part:
	//
	//	*StoreFileRequest_StoreFile
	//	*StoreFileRequest_Chunk
	Part isStoreFileRequest_Part `protobuf_oneof:"part"`
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{0}
}

func (m *StoreFileRequest) GetPart() isStoreFileRequest_Part {
	if m != nil {
		return m.Part
	}
	return nil
}

func (x *StoreFileRequest) GetStoreFile() *StoreFile {
	if x, ok := x.GetPart().(*StoreFileRequest_StoreFile); ok {
		return x.StoreFile
	}
	return nil
}

func (x *StoreFileRequest) GetChunk() []byte {
	if x, ok := x.GetPart().(*StoreFileRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isStoreFileRequest_Part interface {
	isStoreFileRequest_Part()
}

type StoreFileRequest_StoreFile struct {
	StoreFile *StoreFile `protobuf:"bytes,1,opt,name=store_file,json=storeFile,proto3,oneof"`
}

type StoreFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*StoreFileRequest_StoreFile) isStoreFileRequest_Part() {}

func (*StoreFileRequest_Chunk) isStoreFileRequest_Part() {}

type StoreRevisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Part:
	//
	//	*StoreRevisionRequest_StoreRevision
	//	*StoreRevisionRequest_Chunk
	Part isStoreRevisionRequest_Part `protobuf_oneof:"part"`
}

func (x *StoreRevisionRequest) Reset() {
	*x = StoreRevisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRevisionRequest) ProtoMessage() {}

func (x *StoreRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRevisionRequest.ProtoReflect.Descriptor instead.
func (*StoreRevisionRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{1}
}

func (m *StoreRevisionRequest) GetPart() isStoreRevisionRequest_Part {
	if m != nil {
		return m.Part
	}
	return nil
}

func (x *StoreRevisionRequest) GetStoreRevision() *StoreRevision {
	if x, ok := x.GetPart().(*StoreRevisionRequest_StoreRevision); ok {
		return x.StoreRevision
	}
	return nil
}

func (x *StoreRevisionRequest) GetChunk() []byte {
	if x, ok := x.GetPart().(*StoreRevisionRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isStoreRevisionRequest_Part interface {
	isStoreRevisionRequest_Part()
}

type StoreRevisionRequest_StoreRevision struct {
	StoreRevision *StoreRevision `protobuf:"bytes,1,opt,name=store_revision,json=storeRevision,proto3,oneof"`
}

type StoreRevisionRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*StoreRevisionRequest_StoreRevision) isStoreRevisionRequest_Part() {}

func (*StoreRevisionRequest_Chunk) isStoreRevisionRequest_Part() {}

type StoreFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // TODO identity how cloud events define origin and reuse it
}

func (x *StoreFile) Reset() {
	*x = StoreFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFile) ProtoMessage() {}

func (x *StoreFile) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFile.ProtoReflect.Descriptor instead.
func (*StoreFile) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{2}
}

func (x *StoreFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StoreRevision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId    *protobuf.Uuid `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	StoreFile *StoreFile     `protobuf:"bytes,2,opt,name=store_file,json=storeFile,proto3" json:"store_file,omitempty"`
}

func (x *StoreRevision) Reset() {
	*x = StoreRevision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRevision) ProtoMessage() {}

func (x *StoreRevision) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRevision.ProtoReflect.Descriptor instead.
func (*StoreRevision) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StoreRevision) GetFileId() *protobuf.Uuid {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *StoreRevision) GetStoreFile() *StoreFile {
	if x != nil {
		return x.StoreFile
	}
	return nil
}

type StoreFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoredFile *StoredFile `protobuf:"bytes,1,opt,name=stored_file,json=storedFile,proto3" json:"stored_file,omitempty"`
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{4}
}

func (x *StoreFileResponse) GetStoredFile() *StoredFile {
	if x != nil {
		return x.StoredFile
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId *protobuf.Uuid `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadFileRequest) GetFileId() *protobuf.Uuid {
	if x != nil {
		return x.FileId
	}
	return nil
}

type DownloadRevisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId     *protobuf.Uuid `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	RevisionId *protobuf.Uuid `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
}

func (x *DownloadRevisionRequest) Reset() {
	*x = DownloadRevisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRevisionRequest) ProtoMessage() {}

func (x *DownloadRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRevisionRequest.ProtoReflect.Descriptor instead.
func (*DownloadRevisionRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadRevisionRequest) GetFileId() *protobuf.Uuid {
	if x != nil {
		return x.FileId
	}
	return nil
}

func (x *DownloadRevisionRequest) GetRevisionId() *protobuf.Uuid {
	if x != nil {
		return x.RevisionId
	}
	return nil
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The first message are the file id and the metadata
	// The following messages sequential chunks of the file
	// The file ends when the stream ends
	//
	// Types that are assignable to Part:
	//
	//	*DownloadFileResponse_StoredFile
	//	*DownloadFileResponse_Chunk
	Part isDownloadFileResponse_Part `protobuf_oneof:"part"`
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{7}
}

func (m *DownloadFileResponse) GetPart() isDownloadFileResponse_Part {
	if m != nil {
		return m.Part
	}
	return nil
}

func (x *DownloadFileResponse) GetStoredFile() *StoredFile {
	if x, ok := x.GetPart().(*DownloadFileResponse_StoredFile); ok {
		return x.StoredFile
	}
	return nil
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x, ok := x.GetPart().(*DownloadFileResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isDownloadFileResponse_Part interface {
	isDownloadFileResponse_Part()
}

type DownloadFileResponse_StoredFile struct {
	StoredFile *StoredFile `protobuf:"bytes,1,opt,name=stored_file,json=storedFile,proto3,oneof"`
}

type DownloadFileResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*DownloadFileResponse_StoredFile) isDownloadFileResponse_Part() {}

func (*DownloadFileResponse_Chunk) isDownloadFileResponse_Part() {}

var File_kinnekode_restaurant_file_v1_file_service_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0a, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a,
	0x04, 0x70, 0x61, 0x72, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54,
	0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04,
	0x70, 0x61, 0x72, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75,
	0x69, 0x64, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x0a, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0x5e, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b,
	0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0x48, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x55, 0x75, 0x69, 0x64, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x87, 0x01, 0x0a,
	0x17, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55,
	0x75, 0x69, 0x64, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0b, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4b, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00,
	0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x74, 0x32, 0xef, 0x03, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x09,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2e, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x76, 0x0a, 0x0d,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x2e,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2f, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x12, 0x77, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x31, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x7f, 0x0a,
	0x10, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x35, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x48,
	0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData = file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc
)

func file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData)
	})
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData
}

var file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kinnekode_restaurant_file_v1_file_service_proto_goTypes = []interface{}{
	(*StoreFileRequest)(nil),        // 0: kinnekode.restaurant.file.v1.StoreFileRequest
	(*StoreRevisionRequest)(nil),    // 1: kinnekode.restaurant.file.v1.StoreRevisionRequest
	(*StoreFile)(nil),               // 2: kinnekode.restaurant.file.v1.StoreFile
	(*StoreRevision)(nil),           // 3: kinnekode.restaurant.file.v1.StoreRevision
	(*StoreFileResponse)(nil),       // 4: kinnekode.restaurant.file.v1.StoreFileResponse
	(*DownloadFileRequest)(nil),     // 5: kinnekode.restaurant.file.v1.DownloadFileRequest
	(*DownloadRevisionRequest)(nil), // 6: kinnekode.restaurant.file.v1.DownloadRevisionRequest
	(*DownloadFileResponse)(nil),    // 7: kinnekode.restaurant.file.v1.DownloadFileResponse
	(*protobuf.Uuid)(nil),           // 8: kinnekode.protobuf.Uuid
	(*StoredFile)(nil),              // 9: kinnekode.restaurant.file.v1.StoredFile
}
var file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs = []int32{
	2,  // 0: kinnekode.restaurant.file.v1.StoreFileRequest.store_file:type_name -> kinnekode.restaurant.file.v1.StoreFile
	3,  // 1: kinnekode.restaurant.file.v1.StoreRevisionRequest.store_revision:type_name -> kinnekode.restaurant.file.v1.StoreRevision
	8,  // 2: kinnekode.restaurant.file.v1.StoreRevision.file_id:type_name -> kinnekode.protobuf.Uuid
	2,  // 3: kinnekode.restaurant.file.v1.StoreRevision.store_file:type_name -> kinnekode.restaurant.file.v1.StoreFile
	9,  // 4: kinnekode.restaurant.file.v1.StoreFileResponse.stored_file:type_name -> kinnekode.restaurant.file.v1.StoredFile
	8,  // 5: kinnekode.restaurant.file.v1.DownloadFileRequest.file_id:type_name -> kinnekode.protobuf.Uuid
	8,  // 6: kinnekode.restaurant.file.v1.DownloadRevisionRequest.file_id:type_name -> kinnekode.protobuf.Uuid
	8,  // 7: kinnekode.restaurant.file.v1.DownloadRevisionRequest.revision_id:type_name -> kinnekode.protobuf.Uuid
	9,  // 8: kinnekode.restaurant.file.v1.DownloadFileResponse.stored_file:type_name -> kinnekode.restaurant.file.v1.StoredFile
	0,  // 9: kinnekode.restaurant.file.v1.FileService.StoreFile:input_type -> kinnekode.restaurant.file.v1.StoreFileRequest
	1,  // 10: kinnekode.restaurant.file.v1.FileService.StoreRevision:input_type -> kinnekode.restaurant.file.v1.StoreRevisionRequest
	5,  // 11: kinnekode.restaurant.file.v1.FileService.DownloadFile:input_type -> kinnekode.restaurant.file.v1.DownloadFileRequest
	6,  // 12: kinnekode.restaurant.file.v1.FileService.DownloadRevision:input_type -> kinnekode.restaurant.file.v1.DownloadRevisionRequest
	4,  // 13: kinnekode.restaurant.file.v1.FileService.StoreFile:output_type -> kinnekode.restaurant.file.v1.StoreFileResponse
	4,  // 14: kinnekode.restaurant.file.v1.FileService.StoreRevision:output_type -> kinnekode.restaurant.file.v1.StoreFileResponse
	7,  // 15: kinnekode.restaurant.file.v1.FileService.DownloadFile:output_type -> kinnekode.restaurant.file.v1.DownloadFileResponse
	7,  // 16: kinnekode.restaurant.file.v1.FileService.DownloadRevision:output_type -> kinnekode.restaurant.file.v1.DownloadFileResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_file_v1_file_service_proto_init() }
func file_kinnekode_restaurant_file_v1_file_service_proto_init() {
	if File_kinnekode_restaurant_file_v1_file_service_proto != nil {
		return
	}
	file_kinnekode_restaurant_file_v1_file_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRevisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreRevision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRevisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StoreFileRequest_StoreFile)(nil),
		(*StoreFileRequest_Chunk)(nil),
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*StoreRevisionRequest_StoreRevision)(nil),
		(*StoreRevisionRequest_Chunk)(nil),
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*DownloadFileResponse_StoredFile)(nil),
		(*DownloadFileResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinnekode_restaurant_file_v1_file_service_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs,
		MessageInfos:      file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_file_v1_file_service_proto = out.File
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc = nil
	file_kinnekode_restaurant_file_v1_file_service_proto_goTypes = nil
	file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs = nil
}
