// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.0
// source: kinnekode/restaurant/file/v1/file_service.proto

package v1

import (
	protobuf "github.com/kinneko-de/api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to File:
	//
	//	*StoreFileRequest_Name
	//	*StoreFileRequest_Chunk
	File isStoreFileRequest_File `protobuf_oneof:"file"`
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{0}
}

func (m *StoreFileRequest) GetFile() isStoreFileRequest_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (x *StoreFileRequest) GetName() string {
	if x, ok := x.GetFile().(*StoreFileRequest_Name); ok {
		return x.Name
	}
	return ""
}

func (x *StoreFileRequest) GetChunk() []byte {
	if x, ok := x.GetFile().(*StoreFileRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isStoreFileRequest_File interface {
	isStoreFileRequest_File()
}

type StoreFileRequest_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type StoreFileRequest_Chunk struct {
	// TODO identity how cloud events define origin and reuse it
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*StoreFileRequest_Name) isStoreFileRequest_File() {}

func (*StoreFileRequest_Chunk) isStoreFileRequest_File() {}

type StoreFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoredFile         *StoredFile         `protobuf:"bytes,1,opt,name=stored_file,json=storedFile,proto3" json:"stored_file,omitempty"`
	StoredFileMetadata *StoredFileMetadata `protobuf:"bytes,2,opt,name=stored_file_metadata,json=storedFileMetadata,proto3" json:"stored_file_metadata,omitempty"`
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFileResponse) GetStoredFile() *StoredFile {
	if x != nil {
		return x.StoredFile
	}
	return nil
}

func (x *StoreFileResponse) GetStoredFileMetadata() *StoredFileMetadata {
	if x != nil {
		return x.StoredFileMetadata
	}
	return nil
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Download:
	//
	//	*DownloadFileRequest_FileId
	//	*DownloadFileRequest_RevisionId
	Download isDownloadFileRequest_Download `protobuf_oneof:"download"`
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{2}
}

func (m *DownloadFileRequest) GetDownload() isDownloadFileRequest_Download {
	if m != nil {
		return m.Download
	}
	return nil
}

func (x *DownloadFileRequest) GetFileId() *protobuf.Uuid {
	if x, ok := x.GetDownload().(*DownloadFileRequest_FileId); ok {
		return x.FileId
	}
	return nil
}

func (x *DownloadFileRequest) GetRevisionId() *protobuf.Uuid {
	if x, ok := x.GetDownload().(*DownloadFileRequest_RevisionId); ok {
		return x.RevisionId
	}
	return nil
}

type isDownloadFileRequest_Download interface {
	isDownloadFileRequest_Download()
}

type DownloadFileRequest_FileId struct {
	// download the latest revision of the file
	FileId *protobuf.Uuid `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3,oneof"`
}

type DownloadFileRequest_RevisionId struct {
	// download the specific revision of the file
	RevisionId *protobuf.Uuid `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3,oneof"`
}

func (*DownloadFileRequest_FileId) isDownloadFileRequest_Download() {}

func (*DownloadFileRequest_RevisionId) isDownloadFileRequest_Download() {}

type DownloadFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The first message are the file metadata
	// The next messages are only chunks of the file in order
	// On end of stream the file is ended
	//
	// Types that are assignable to File:
	//
	//	*DownloadFileResponse_Metadata
	//	*DownloadFileResponse_Chunk
	File isDownloadFileResponse_File `protobuf_oneof:"file"`
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP(), []int{3}
}

func (m *DownloadFileResponse) GetFile() isDownloadFileResponse_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (x *DownloadFileResponse) GetMetadata() *StoredFileMetadata {
	if x, ok := x.GetFile().(*DownloadFileResponse_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (x *DownloadFileResponse) GetChunk() []byte {
	if x, ok := x.GetFile().(*DownloadFileResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isDownloadFileResponse_File interface {
	isDownloadFileResponse_File()
}

type DownloadFileResponse_Metadata struct {
	Metadata *StoredFileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type DownloadFileResponse_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*DownloadFileResponse_Metadata) isDownloadFileResponse_File() {}

func (*DownloadFileResponse_Chunk) isDownloadFileResponse_File() {}

var File_kinnekode_restaurant_file_v1_file_service_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1c, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a,
	0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0xc2, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6b,
	0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x62, 0x0a, 0x14, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x75,
	0x69, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x42, 0x0a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x86, 0x01, 0x0a,
	0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x32, 0xf6, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6e, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x2e, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x77, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x31, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64,
	0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x48,
	0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData = file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc
)

func file_kinnekode_restaurant_file_v1_file_service_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData)
	})
	return file_kinnekode_restaurant_file_v1_file_service_proto_rawDescData
}

var file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kinnekode_restaurant_file_v1_file_service_proto_goTypes = []interface{}{
	(*StoreFileRequest)(nil),     // 0: kinnekode.restaurant.file.v1.StoreFileRequest
	(*StoreFileResponse)(nil),    // 1: kinnekode.restaurant.file.v1.StoreFileResponse
	(*DownloadFileRequest)(nil),  // 2: kinnekode.restaurant.file.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 3: kinnekode.restaurant.file.v1.DownloadFileResponse
	(*StoredFile)(nil),           // 4: kinnekode.restaurant.file.v1.StoredFile
	(*StoredFileMetadata)(nil),   // 5: kinnekode.restaurant.file.v1.StoredFileMetadata
	(*protobuf.Uuid)(nil),        // 6: kinnekode.protobuf.Uuid
}
var file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs = []int32{
	4, // 0: kinnekode.restaurant.file.v1.StoreFileResponse.stored_file:type_name -> kinnekode.restaurant.file.v1.StoredFile
	5, // 1: kinnekode.restaurant.file.v1.StoreFileResponse.stored_file_metadata:type_name -> kinnekode.restaurant.file.v1.StoredFileMetadata
	6, // 2: kinnekode.restaurant.file.v1.DownloadFileRequest.file_id:type_name -> kinnekode.protobuf.Uuid
	6, // 3: kinnekode.restaurant.file.v1.DownloadFileRequest.revision_id:type_name -> kinnekode.protobuf.Uuid
	5, // 4: kinnekode.restaurant.file.v1.DownloadFileResponse.metadata:type_name -> kinnekode.restaurant.file.v1.StoredFileMetadata
	0, // 5: kinnekode.restaurant.file.v1.FileService.StoreFile:input_type -> kinnekode.restaurant.file.v1.StoreFileRequest
	2, // 6: kinnekode.restaurant.file.v1.FileService.DownloadFile:input_type -> kinnekode.restaurant.file.v1.DownloadFileRequest
	1, // 7: kinnekode.restaurant.file.v1.FileService.StoreFile:output_type -> kinnekode.restaurant.file.v1.StoreFileResponse
	3, // 8: kinnekode.restaurant.file.v1.FileService.DownloadFile:output_type -> kinnekode.restaurant.file.v1.DownloadFileResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_file_v1_file_service_proto_init() }
func file_kinnekode_restaurant_file_v1_file_service_proto_init() {
	if File_kinnekode_restaurant_file_v1_file_service_proto != nil {
		return
	}
	file_kinnekode_restaurant_file_v1_file_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*StoreFileRequest_Name)(nil),
		(*StoreFileRequest_Chunk)(nil),
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*DownloadFileRequest_FileId)(nil),
		(*DownloadFileRequest_RevisionId)(nil),
	}
	file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*DownloadFileResponse_Metadata)(nil),
		(*DownloadFileResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinnekode_restaurant_file_v1_file_service_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs,
		MessageInfos:      file_kinnekode_restaurant_file_v1_file_service_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_file_v1_file_service_proto = out.File
	file_kinnekode_restaurant_file_v1_file_service_proto_rawDesc = nil
	file_kinnekode_restaurant_file_v1_file_service_proto_goTypes = nil
	file_kinnekode_restaurant_file_v1_file_service_proto_depIdxs = nil
}
