// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: kinnekode/restaurant/document/design/v1/template_api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateAPI_ListTemplates_FullMethodName = "/kinnekode.restaurant.document.design.v1.TemplateAPI/ListTemplates"
)

// TemplateAPIClient is the client API for TemplateAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public visible api for template management
type TemplateAPIClient interface {
	// List of crated templates for a quick overview
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
}

type templateAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateAPIClient(cc grpc.ClientConnInterface) TemplateAPIClient {
	return &templateAPIClient{cc}
}

func (c *templateAPIClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, TemplateAPI_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateAPIServer is the server API for TemplateAPI service.
// All implementations must embed UnimplementedTemplateAPIServer
// for forward compatibility.
//
// Public visible api for template management
type TemplateAPIServer interface {
	// List of crated templates for a quick overview
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	mustEmbedUnimplementedTemplateAPIServer()
}

// UnimplementedTemplateAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateAPIServer struct{}

func (UnimplementedTemplateAPIServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedTemplateAPIServer) mustEmbedUnimplementedTemplateAPIServer() {}
func (UnimplementedTemplateAPIServer) testEmbeddedByValue()                     {}

// UnsafeTemplateAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateAPIServer will
// result in compilation errors.
type UnsafeTemplateAPIServer interface {
	mustEmbedUnimplementedTemplateAPIServer()
}

func RegisterTemplateAPIServer(s grpc.ServiceRegistrar, srv TemplateAPIServer) {
	// If the following call pancis, it indicates UnimplementedTemplateAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateAPI_ServiceDesc, srv)
}

func _TemplateAPI_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateAPIServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateAPI_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateAPIServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateAPI_ServiceDesc is the grpc.ServiceDesc for TemplateAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kinnekode.restaurant.document.design.v1.TemplateAPI",
	HandlerType: (*TemplateAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTemplates",
			Handler:    _TemplateAPI_ListTemplates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kinnekode/restaurant/document/design/v1/template_api.proto",
}
