// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.0
// source: kinnekode/protobuf/uuid.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Universally Unique Identifier (https://www.rfc-editor.org/rfc/rfc4122)
type Uuid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Example: 550e8400-e29b-11d4-a716-446655440000
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Uuid) Reset() {
	*x = Uuid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_protobuf_uuid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uuid) ProtoMessage() {}

func (x *Uuid) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_protobuf_uuid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uuid.ProtoReflect.Descriptor instead.
func (*Uuid) Descriptor() ([]byte, []int) {
	return file_kinnekode_protobuf_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *Uuid) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kinnekode_protobuf_uuid_proto protoreflect.FileDescriptor

var file_kinnekode_protobuf_uuid_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x12, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b,
	0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_protobuf_uuid_proto_rawDescOnce sync.Once
	file_kinnekode_protobuf_uuid_proto_rawDescData = file_kinnekode_protobuf_uuid_proto_rawDesc
)

func file_kinnekode_protobuf_uuid_proto_rawDescGZIP() []byte {
	file_kinnekode_protobuf_uuid_proto_rawDescOnce.Do(func() {
		file_kinnekode_protobuf_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_protobuf_uuid_proto_rawDescData)
	})
	return file_kinnekode_protobuf_uuid_proto_rawDescData
}

var file_kinnekode_protobuf_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kinnekode_protobuf_uuid_proto_goTypes = []interface{}{
	(*Uuid)(nil), // 0: kinnekode.protobuf.Uuid
}
var file_kinnekode_protobuf_uuid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kinnekode_protobuf_uuid_proto_init() }
func file_kinnekode_protobuf_uuid_proto_init() {
	if File_kinnekode_protobuf_uuid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_protobuf_uuid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uuid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_protobuf_uuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kinnekode_protobuf_uuid_proto_goTypes,
		DependencyIndexes: file_kinnekode_protobuf_uuid_proto_depIdxs,
		MessageInfos:      file_kinnekode_protobuf_uuid_proto_msgTypes,
	}.Build()
	File_kinnekode_protobuf_uuid_proto = out.File
	file_kinnekode_protobuf_uuid_proto_rawDesc = nil
	file_kinnekode_protobuf_uuid_proto_goTypes = nil
	file_kinnekode_protobuf_uuid_proto_depIdxs = nil
}
