// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/restaurant/document/v1/dummy_service.proto

package v1

import (
	protobuf "github.com/kinneko-de/api-contract/golang/kinnekode/protobuf"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadDocumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to File:
	//
	//	*UploadDocumentRequest_Metadata_
	//	*UploadDocumentRequest_Chunk
	File isUploadDocumentRequest_File `protobuf_oneof:"file"`
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescGZIP(), []int{0}
}

func (m *UploadDocumentRequest) GetFile() isUploadDocumentRequest_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (x *UploadDocumentRequest) GetMetadata() *UploadDocumentRequest_Metadata {
	if x, ok := x.GetFile().(*UploadDocumentRequest_Metadata_); ok {
		return x.Metadata
	}
	return nil
}

func (x *UploadDocumentRequest) GetChunk() []byte {
	if x, ok := x.GetFile().(*UploadDocumentRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isUploadDocumentRequest_File interface {
	isUploadDocumentRequest_File()
}

type UploadDocumentRequest_Metadata_ struct {
	Metadata *UploadDocumentRequest_Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadDocumentRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadDocumentRequest_Metadata_) isUploadDocumentRequest_File() {}

func (*UploadDocumentRequest_Chunk) isUploadDocumentRequest_File() {}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId *protobuf.Uuid `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadDocumentResponse) GetDocumentId() *protobuf.Uuid {
	if x != nil {
		return x.DocumentId
	}
	return nil
}

type UploadDocumentRequest_Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId *protobuf.Uuid `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Name      string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UploadDocumentRequest_Metadata) Reset() {
	*x = UploadDocumentRequest_Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadDocumentRequest_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest_Metadata) ProtoMessage() {}

func (x *UploadDocumentRequest_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest_Metadata.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest_Metadata) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UploadDocumentRequest_Metadata) GetRequestId() *protobuf.Uuid {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *UploadDocumentRequest_Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_kinnekode_restaurant_document_v1_dummy_service_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64,
	0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x75, 0x69,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x5e, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e,
	0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x57, 0x0a, 0x08, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55,
	0x75, 0x69, 0x64, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x53, 0x0a, 0x16, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55,
	0x75, 0x69, 0x64, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32,
	0x99, 0x01, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x85, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x37, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x38, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x4c, 0x5a, 0x4a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b,
	0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f,
	0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescData = file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDesc
)

func file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescData)
	})
	return file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDescData
}

var file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kinnekode_restaurant_document_v1_dummy_service_proto_goTypes = []interface{}{
	(*UploadDocumentRequest)(nil),          // 0: kinnekode.restaurant.document.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil),         // 1: kinnekode.restaurant.document.v1.UploadDocumentResponse
	(*UploadDocumentRequest_Metadata)(nil), // 2: kinnekode.restaurant.document.v1.UploadDocumentRequest.Metadata
	(*protobuf.Uuid)(nil),                  // 3: kinnekode.protobuf.Uuid
}
var file_kinnekode_restaurant_document_v1_dummy_service_proto_depIdxs = []int32{
	2, // 0: kinnekode.restaurant.document.v1.UploadDocumentRequest.metadata:type_name -> kinnekode.restaurant.document.v1.UploadDocumentRequest.Metadata
	3, // 1: kinnekode.restaurant.document.v1.UploadDocumentResponse.document_id:type_name -> kinnekode.protobuf.Uuid
	3, // 2: kinnekode.restaurant.document.v1.UploadDocumentRequest.Metadata.request_id:type_name -> kinnekode.protobuf.Uuid
	0, // 3: kinnekode.restaurant.document.v1.DocumentService.UploadDocument:input_type -> kinnekode.restaurant.document.v1.UploadDocumentRequest
	1, // 4: kinnekode.restaurant.document.v1.DocumentService.UploadDocument:output_type -> kinnekode.restaurant.document.v1.UploadDocumentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_document_v1_dummy_service_proto_init() }
func file_kinnekode_restaurant_document_v1_dummy_service_proto_init() {
	if File_kinnekode_restaurant_document_v1_dummy_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadDocumentRequest_Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UploadDocumentRequest_Metadata_)(nil),
		(*UploadDocumentRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kinnekode_restaurant_document_v1_dummy_service_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_document_v1_dummy_service_proto_depIdxs,
		MessageInfos:      file_kinnekode_restaurant_document_v1_dummy_service_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_document_v1_dummy_service_proto = out.File
	file_kinnekode_restaurant_document_v1_dummy_service_proto_rawDesc = nil
	file_kinnekode_restaurant_document_v1_dummy_service_proto_goTypes = nil
	file_kinnekode_restaurant_document_v1_dummy_service_proto_depIdxs = nil
}
