// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: kinnekode/restaurant/document/v1/generate_document.proto

package v1

import (
	v1 "github.com/kinneko-de/api-contract/golang/kinnekode/restaurant/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestedDocument_OutputFormat int32

const (
	RequestedDocument_OUTPUT_FORMAT_UNSPECIFIED RequestedDocument_OutputFormat = 0
	RequestedDocument_OUTPUT_FORMAT_PDF         RequestedDocument_OutputFormat = 1
)

// Enum value maps for RequestedDocument_OutputFormat.
var (
	RequestedDocument_OutputFormat_name = map[int32]string{
		0: "OUTPUT_FORMAT_UNSPECIFIED",
		1: "OUTPUT_FORMAT_PDF",
	}
	RequestedDocument_OutputFormat_value = map[string]int32{
		"OUTPUT_FORMAT_UNSPECIFIED": 0,
		"OUTPUT_FORMAT_PDF":         1,
	}
)

func (x RequestedDocument_OutputFormat) Enum() *RequestedDocument_OutputFormat {
	p := new(RequestedDocument_OutputFormat)
	*p = x
	return p
}

func (x RequestedDocument_OutputFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestedDocument_OutputFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_kinnekode_restaurant_document_v1_generate_document_proto_enumTypes[0].Descriptor()
}

func (RequestedDocument_OutputFormat) Type() protoreflect.EnumType {
	return &file_kinnekode_restaurant_document_v1_generate_document_proto_enumTypes[0]
}

func (x RequestedDocument_OutputFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestedDocument_OutputFormat.Descriptor instead.
func (RequestedDocument_OutputFormat) EnumDescriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescGZIP(), []int{1, 0}
}

// Request to generate a document
// Is a command message and uses request/reply pattern
// Reply will be an event of type DocumentGenerated
type GenerateDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request            *v1.Request          `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	RequestedDocuments []*RequestedDocument `protobuf:"bytes,2,rep,name=requested_documents,json=requestedDocuments,proto3" json:"requested_documents,omitempty"`
}

func (x *GenerateDocument) Reset() {
	*x = GenerateDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDocument) ProtoMessage() {}

func (x *GenerateDocument) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDocument.ProtoReflect.Descriptor instead.
func (*GenerateDocument) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDocument) GetRequest() *v1.Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GenerateDocument) GetRequestedDocuments() []*RequestedDocument {
	if x != nil {
		return x.RequestedDocuments
	}
	return nil
}

type RequestedDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputFormats []RequestedDocument_OutputFormat `protobuf:"varint,1,rep,packed,name=output_formats,json=outputFormats,proto3,enum=kinnekode.restaurant.document.v1.RequestedDocument_OutputFormat" json:"output_formats,omitempty"`
	// Types that are assignable to Type:
	//
	//	*RequestedDocument_Invoice
	Type isRequestedDocument_Type `protobuf_oneof:"type"`
}

func (x *RequestedDocument) Reset() {
	*x = RequestedDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedDocument) ProtoMessage() {}

func (x *RequestedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedDocument.ProtoReflect.Descriptor instead.
func (*RequestedDocument) Descriptor() ([]byte, []int) {
	return file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescGZIP(), []int{1}
}

func (x *RequestedDocument) GetOutputFormats() []RequestedDocument_OutputFormat {
	if x != nil {
		return x.OutputFormats
	}
	return nil
}

func (m *RequestedDocument) GetType() isRequestedDocument_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *RequestedDocument) GetInvoice() *Invoice {
	if x, ok := x.GetType().(*RequestedDocument_Invoice); ok {
		return x.Invoice
	}
	return nil
}

type isRequestedDocument_Type interface {
	isRequestedDocument_Type()
}

type RequestedDocument_Invoice struct {
	Invoice *Invoice `protobuf:"bytes,2,opt,name=invoice,proto3,oneof"`
}

func (*RequestedDocument_Invoice) isRequestedDocument_Type() {}

var File_kinnekode_restaurant_document_v1_generate_document_proto protoreflect.FileDescriptor

var file_kinnekode_restaurant_document_v1_generate_document_proto_rawDesc = []byte{
	0x0a, 0x38, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x25, 0x6b, 0x69,
	0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61,
	0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x64, 0x0a, 0x13, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x5f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x91, 0x02, 0x0a, 0x11, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x67, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x40, 0x2e, 0x6b, 0x69, 0x6e, 0x6e, 0x65,
	0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x2e,
	0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0d, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x12, 0x45, 0x0a, 0x07, 0x69, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x2e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x22, 0x44, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x1d, 0x0a, 0x19, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41,
	0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x15, 0x0a, 0x11, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54,
	0x5f, 0x50, 0x44, 0x46, 0x10, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x4c,
	0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x6e,
	0x6e, 0x65, 0x6b, 0x6f, 0x2d, 0x64, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x6b, 0x69, 0x6e, 0x6e,
	0x65, 0x6b, 0x6f, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74,
	0x2f, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescOnce sync.Once
	file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescData = file_kinnekode_restaurant_document_v1_generate_document_proto_rawDesc
)

func file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescGZIP() []byte {
	file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescOnce.Do(func() {
		file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescData)
	})
	return file_kinnekode_restaurant_document_v1_generate_document_proto_rawDescData
}

var file_kinnekode_restaurant_document_v1_generate_document_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kinnekode_restaurant_document_v1_generate_document_proto_goTypes = []interface{}{
	(RequestedDocument_OutputFormat)(0), // 0: kinnekode.restaurant.document.v1.RequestedDocument.OutputFormat
	(*GenerateDocument)(nil),            // 1: kinnekode.restaurant.document.v1.GenerateDocument
	(*RequestedDocument)(nil),           // 2: kinnekode.restaurant.document.v1.RequestedDocument
	(*v1.Request)(nil),                  // 3: kinnekode.restaurant.v1.Request
	(*Invoice)(nil),                     // 4: kinnekode.restaurant.document.v1.Invoice
}
var file_kinnekode_restaurant_document_v1_generate_document_proto_depIdxs = []int32{
	3, // 0: kinnekode.restaurant.document.v1.GenerateDocument.request:type_name -> kinnekode.restaurant.v1.Request
	2, // 1: kinnekode.restaurant.document.v1.GenerateDocument.requested_documents:type_name -> kinnekode.restaurant.document.v1.RequestedDocument
	0, // 2: kinnekode.restaurant.document.v1.RequestedDocument.output_formats:type_name -> kinnekode.restaurant.document.v1.RequestedDocument.OutputFormat
	4, // 3: kinnekode.restaurant.document.v1.RequestedDocument.invoice:type_name -> kinnekode.restaurant.document.v1.Invoice
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kinnekode_restaurant_document_v1_generate_document_proto_init() }
func file_kinnekode_restaurant_document_v1_generate_document_proto_init() {
	if File_kinnekode_restaurant_document_v1_generate_document_proto != nil {
		return
	}
	file_kinnekode_restaurant_document_v1_invoice_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestedDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*RequestedDocument_Invoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kinnekode_restaurant_document_v1_generate_document_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kinnekode_restaurant_document_v1_generate_document_proto_goTypes,
		DependencyIndexes: file_kinnekode_restaurant_document_v1_generate_document_proto_depIdxs,
		EnumInfos:         file_kinnekode_restaurant_document_v1_generate_document_proto_enumTypes,
		MessageInfos:      file_kinnekode_restaurant_document_v1_generate_document_proto_msgTypes,
	}.Build()
	File_kinnekode_restaurant_document_v1_generate_document_proto = out.File
	file_kinnekode_restaurant_document_v1_generate_document_proto_rawDesc = nil
	file_kinnekode_restaurant_document_v1_generate_document_proto_goTypes = nil
	file_kinnekode_restaurant_document_v1_generate_document_proto_depIdxs = nil
}
