on:
  push:
    paths:
      - '.github/workflows/ci-pipeline-restaurant.yml'
      - '.github/workflows/ci-pipeline.yml'
      - 'proto/kinnekode/restaurant/**'
      - 'dotnet/restaurant/**'
      - 'golang/kinnekode/restaurant/**'
      - '!**/**.md'
      - '!doc/**'

concurrency: ci-${{ github.ref }}

name: ci-api-restaurant

jobs:
    ci-api:
      uses: ./.github/workflows/ci-pipeline.yml
      permissions:
        contents: write
        packages: write
      with:
        project: restaurant
        dotnet_solution: dotnet/restaurant/KinNekoDe.ApiContract.Restaurant.sln
        golang_module: golang/kinnekode/restaurant
        major_minor_patch: 0.0.1
      secrets: inherit
