on:
  push:
    paths:
      - '.github/workflows/ci-protobuf.yml'
      - '.github/workflows/ci.yml'
      - 'proto/kinnekode/protobuf/**'
      - 'dotnet/protobuf/**'
      - 'golang/kinnekode/protobuf/**'
      - 'scripts/**'
      - '!**/**.md'
      - '!doc/**'

concurrency: ci-api-protobuf-${{ github.ref }}

name: ci-api-protobuf

jobs:
    ci-api:
      uses: ./.github/workflows/ci.yml
      permissions:
        contents: write
        packages: write
      with:
        project: protobuf
        dotnet_solution: dotnet/protobuf/KinNekoDe.ApiContract.Protobuf.sln
        golang_module: golang/kinnekode/protobuf
        major_minor_patch: 0.2.13
      secrets: inherit
