on:
  push:
    paths:
      - '.github/workflows/protobuf-pipeline.yml'
      - 'proto/kinnekode/protobuf/**'
      - 'dotnet/protobuf/**'
      - 'golang/kinnekode/protobuf/**'
      - '!**/**.md'
      - '!doc/**'

permissions:
  contents: write
  packages: write

concurrency: ci-${{ github.ref }}

name: apicontract-protobuf

jobs:
    ci-api:
      uses: ./.github/workflows/pipeline.yml
      with:
        project: protobuf
        dotnet_solution: dotnet/protobuf/KinNekoDe.ApiContract.Protobuf.sln
        golang_module: golang/kinnekode/protobuf
        major_minor_patch: 0.1.0
